change check assembly git action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -125,5 +125,12 @@ jobs:
 
       - name: Check assembly
         run: |
-          echo "Benchmark assembly failed."
-          exit 1
+          cat .tests/results/benchmarking/assembly.csv
+          if (tail -1 .tests/results/benchmarking/assembly.csv > 0)
+          then
+            echo "Assembly failed."
+            exit 1
+          else
+            echo "Assembly was successful."
+          if
+
