matrix test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,9 +37,14 @@ jobs:
 
   Testing:
     runs-on: ubuntu-latest
+
     needs:
       - Formatting
       - Linting
+    
+    strategy:
+      matrix:
+        rule: [all, benchmark_strain_calling, benchmark_assembly]
     steps:
       - uses: actions/checkout@v2
 
@@ -97,7 +102,7 @@ jobs:
           directory: .tests
           snakefile: workflow/Snakefile
           stagein: mamba install -n snakemake -c conda-forge peppy -y
-          args: "--use-conda --show-failed-logs --cores 2 --resources ncbi_api_requests=1 --conda-cleanup-pkgs cache --conda-frontend mamba"
+          args: "--use-conda --show-failed-logs --cores 2 --resources ncbi_api_requests=1 --conda-cleanup-pkgs cache --conda-frontend mamba ${{ matrix.rule }}"
 
       # - name: Test input changes
       #   uses: snakemake/snakemake-github-action@v1.15.0
@@ -146,149 +151,149 @@ jobs:
       #     stagein: mamba install -n snakemake -c conda-forge peppy
       #     args: "--generate-unit-tests"
 
-      - name: Test workflow (singularity)
-        uses: snakemake/snakemake-github-action@v1.15.0
-        with:
-          directory: .tests
-          snakefile: workflow/Snakefile
-          stagein: mamba install -n snakemake -c conda-forge peppy
-          args: "--use-conda --use-singularity --show-failed-logs --cores 2 --resources ncbi_api_requests=1 --conda-cleanup-pkgs cache --conda-frontend mamba"
+      # - name: Test workflow (singularity)
+      #   uses: snakemake/snakemake-github-action@v1.15.0
+      #   with:
+      #     directory: .tests
+      #     snakefile: workflow/Snakefile
+      #     stagein: mamba install -n snakemake -c conda-forge peppy
+      #     args: "--use-conda --use-singularity --show-failed-logs --cores 2 --resources ncbi_api_requests=1 --conda-cleanup-pkgs cache --conda-frontend mamba"
 
       - name: Change permissions for caching
         run: sudo chmod -R 755 .tests/.snakemake/conda
 
 
-  Strain-Calling-Benchmark:
-    runs-on: ubuntu-latest
-    needs:
-      - Formatting
-      - Linting
-    steps:
-      - uses: actions/checkout@v2
+  # Strain-Calling-Benchmark:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - Formatting
+  #     - Linting
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-      - name: Cache resources
-        id: benchmark-strain-calling-resources
-        uses: actions/cache@v2
-        with:
-          path: |
-            .tests/resources
-          key: ${{ runner.os }}-benchmark-resources-${{ hashFiles('**.tests/resources**taxo.k2d') }}
-          restore-keys: |
-            ${{ runner.os }}-benchmark-resources-${{ hashFiles('**.tests/resources**taxo.k2d') }}
-            ${{ runner.os }}-benchmark-resources-
-
-
-      - name: Cache dependencies
-        id: benchmark-strain-calling-dependencies
-        uses: actions/cache@v2
-        with:
-          path: |
-            .tests/.snakemake/conda
-          key: ${{ runner.os }}-sars-cov-dependencies-${{ hashFiles('*.tests/.snakemake/conda/*.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-sars-cov-dependencies-${{ hashFiles('*.tests/.snakemake/conda/*.yaml') }}
-            ${{ runner.os }}-sars-cov-dependencies-
-
-      - name: Benchmarking the strain calls
-        uses: snakemake/snakemake-github-action@v1.15.0
-        with:
-          directory: .tests
-          snakefile: workflow/Snakefile
-          stagein: mamba install -n snakemake -c conda-forge peppy
-          args: "benchmark_strain_calling --use-conda --show-failed-logs --cores 2 --resources ncbi_api_requests=1 --conda-cleanup-pkgs cache --conda-frontend mamba"
-
-      - name: Get report
-        uses: snakemake/snakemake-github-action@v1.15.0
-        with:
-          directory: .tests
-          snakefile: workflow/Snakefile
-          stagein: mamba install -n snakemake -c conda-forge peppy
-          args: "benchmark_strain_calling --report benchmark-strain-calling-report.zip"
-
-      - name: Upload report
-        uses: actions/upload-artifact@v2
-        with:
-          name: strain-calling-benchmark-report
-          path: .tests/benchmark-strain-calling-report.zip
-
-      - name: Check strain calling
-        run: |
-          cat .tests/results/benchmarking/strain-calling.csv
-          if (tail -n+2 .tests/results/benchmarking/strain-calling.csv | grep mismatch > /dev/null)
-          then
-            echo "Strain calling failed in some cases (see above)."
-            exit 1
-          else
-            echo "Strain calling was successful in all cases."
-          fi
-
-      - name: Change permissions for caching
-        run: sudo chmod -R 755 .tests/.snakemake/conda
+  #     - name: Cache resources
+  #       id: benchmark-strain-calling-resources
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: |
+  #           .tests/resources
+  #         key: ${{ runner.os }}-benchmark-resources-${{ hashFiles('**.tests/resources**taxo.k2d') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-benchmark-resources-${{ hashFiles('**.tests/resources**taxo.k2d') }}
+  #           ${{ runner.os }}-benchmark-resources-
 
 
-  Assembly-Benchmark:
-    runs-on: ubuntu-latest
-    needs:
-      - Formatting
-      - Linting
-    steps:
-      - uses: actions/checkout@v2
+  #     - name: Cache dependencies
+  #       id: benchmark-strain-calling-dependencies
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: |
+  #           .tests/.snakemake/conda
+  #         key: ${{ runner.os }}-sars-cov-dependencies-${{ hashFiles('*.tests/.snakemake/conda/*.yaml') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-sars-cov-dependencies-${{ hashFiles('*.tests/.snakemake/conda/*.yaml') }}
+  #           ${{ runner.os }}-sars-cov-dependencies-
 
-      - name: Cache resources
-        id: benchmark-assembly-resources
-        uses: actions/cache@v2
-        with:
-          path: |
-            .tests/resources
-          key: ${{ runner.os }}-benchmark-resources-${{ hashFiles('**.tests/resources**taxo.k2d') }}
-          restore-keys: |
-            ${{ runner.os }}-benchmark-resources-${{ hashFiles('**.tests/resources**taxo.k2d') }}
-            ${{ runner.os }}-benchmark-resources-
+  #     - name: Benchmarking the strain calls
+  #       uses: snakemake/snakemake-github-action@v1.15.0
+  #       with:
+  #         directory: .tests
+  #         snakefile: workflow/Snakefile
+  #         stagein: mamba install -n snakemake -c conda-forge peppy
+  #         args: "benchmark_strain_calling --use-conda --show-failed-logs --cores 2 --resources ncbi_api_requests=1 --conda-cleanup-pkgs cache --conda-frontend mamba"
+
+  #     - name: Get report
+  #       uses: snakemake/snakemake-github-action@v1.15.0
+  #       with:
+  #         directory: .tests
+  #         snakefile: workflow/Snakefile
+  #         stagein: mamba install -n snakemake -c conda-forge peppy
+  #         args: "benchmark_strain_calling --report benchmark-strain-calling-report.zip"
+
+  #     - name: Upload report
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: strain-calling-benchmark-report
+  #         path: .tests/benchmark-strain-calling-report.zip
+
+  #     - name: Check strain calling
+  #       run: |
+  #         cat .tests/results/benchmarking/strain-calling.csv
+  #         if (tail -n+2 .tests/results/benchmarking/strain-calling.csv | grep mismatch > /dev/null)
+  #         then
+  #           echo "Strain calling failed in some cases (see above)."
+  #           exit 1
+  #         else
+  #           echo "Strain calling was successful in all cases."
+  #         fi
+
+  #     - name: Change permissions for caching
+  #       run: sudo chmod -R 755 .tests/.snakemake/conda
 
 
-      - name: Cache dependencies
-        id: benchmark-assembly-dependencies
-        uses: actions/cache@v2
-        with:
-          path: |
-            .tests/.snakemake/conda
-          key: ${{ runner.os }}-sars-cov-dependencies-${{ hashFiles('*.tests/.snakemake/conda/*.yaml') }}
-          restore-keys: |
-            ${{ runner.os }}-sars-cov-dependencies-${{ hashFiles('*.tests/.snakemake/conda/*.yaml') }}
-            ${{ runner.os }}-sars-cov-dependencies-
+  # Assembly-Benchmark:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - Formatting
+  #     - Linting
+  #   steps:
+  #     - uses: actions/checkout@v2
+
+  #     - name: Cache resources
+  #       id: benchmark-assembly-resources
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: |
+  #           .tests/resources
+  #         key: ${{ runner.os }}-benchmark-resources-${{ hashFiles('**.tests/resources**taxo.k2d') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-benchmark-resources-${{ hashFiles('**.tests/resources**taxo.k2d') }}
+  #           ${{ runner.os }}-benchmark-resources-
+
+
+  #     - name: Cache dependencies
+  #       id: benchmark-assembly-dependencies
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: |
+  #           .tests/.snakemake/conda
+  #         key: ${{ runner.os }}-sars-cov-dependencies-${{ hashFiles('*.tests/.snakemake/conda/*.yaml') }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-sars-cov-dependencies-${{ hashFiles('*.tests/.snakemake/conda/*.yaml') }}
+  #           ${{ runner.os }}-sars-cov-dependencies-
            
-      - name: Benchmarking the assembly
-        uses: snakemake/snakemake-github-action@v1.15.0
-        with:
-          directory: .tests
-          snakefile: workflow/Snakefile
-          stagein: mamba install -n snakemake -c conda-forge peppy
-          args: "benchmark_assembly --use-conda --show-failed-logs --cores 2 --resources ncbi_api_requests=1 --conda-cleanup-pkgs cache --conda-frontend mamba"
+  #     - name: Benchmarking the assembly
+  #       uses: snakemake/snakemake-github-action@v1.15.0
+  #       with:
+  #         directory: .tests
+  #         snakefile: workflow/Snakefile
+  #         stagein: mamba install -n snakemake -c conda-forge peppy
+  #         args: "benchmark_assembly --use-conda --show-failed-logs --cores 2 --resources ncbi_api_requests=1 --conda-cleanup-pkgs cache --conda-frontend mamba"
 
-      - name: Get report
-        uses: snakemake/snakemake-github-action@v1.15.0
-        with:
-          directory: .tests
-          snakefile: workflow/Snakefile
-          stagein: mamba install -n snakemake -c conda-forge peppy
-          args: "benchmark_assembly --report benchmark-assembly-report.zip"
+  #     - name: Get report
+  #       uses: snakemake/snakemake-github-action@v1.15.0
+  #       with:
+  #         directory: .tests
+  #         snakefile: workflow/Snakefile
+  #         stagein: mamba install -n snakemake -c conda-forge peppy
+  #         args: "benchmark_assembly --report benchmark-assembly-report.zip"
 
-      - name: Upload report
-        uses: actions/upload-artifact@v2
-        with:
-          name: assembly-benchmark-report
-          path: .tests/benchmark-assembly-report.zip
+  #     - name: Upload report
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: assembly-benchmark-report
+  #         path: .tests/benchmark-assembly-report.zip
 
-      - name: Check assembly
-        run: |
-          cat .tests/results/benchmarking/assembly.csv
-          if [[ $(tail -1 .tests/results/benchmarking/assembly.csv) < 0.8 ]]
-          then
-            echo "Assembly bechmarking failed. There is at least one assembly where the contigs do not cover 80% of the original sequence (see above)."
-            exit 1
-          else
-            echo "Assembly was successful."
-          fi
+  #     - name: Check assembly
+  #       run: |
+  #         cat .tests/results/benchmarking/assembly.csv
+  #         if [[ $(tail -1 .tests/results/benchmarking/assembly.csv) < 0.8 ]]
+  #         then
+  #           echo "Assembly bechmarking failed. There is at least one assembly where the contigs do not cover 80% of the original sequence (see above)."
+  #           exit 1
+  #         else
+  #           echo "Assembly was successful."
+  #         fi
 
-      - name: Change permissions for caching
-        run: sudo chmod -R 755 .tests/.snakemake/conda
+  #     - name: Change permissions for caching
+  #       run: sudo chmod -R 755 .tests/.snakemake/conda
