check benchmark results

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,33 +36,65 @@ jobs:
   Testing:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v1
-  
-    - name: Cache data
-      uses: actions/cache@v2
-      with:
-        path: |
-          .tests/data
-        key: "testdata" # TODO update key once we cache more than the data
+      - uses: actions/checkout@v1
+    
+      - name: Cache data
+        uses: actions/cache@v2
+        with:
+          path: |
+            .tests/data
+          key: "testdata" # TODO update key once we cache more than the data
 
-    - name: Download test data
-      run: |
-        mkdir -p .tests/data
-        curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR486/002/ERR4861412/ERR4861412_1.fastq.gz > .tests/data/ERR4861412_1.fastq.gz
-        curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR486/002/ERR4861412/ERR4861412_2.fastq.gz > .tests/data/ERR4861412_2.fastq.gz
+      - name: Download test data
+        run: |
+          mkdir -p .tests/data
+          curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR486/002/ERR4861412/ERR4861412_1.fastq.gz > .tests/data/ERR4861412_1.fastq.gz
+          curl -L ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR486/002/ERR4861412/ERR4861412_2.fastq.gz > .tests/data/ERR4861412_2.fastq.gz
 
-    - name: Test workflow
-      uses: snakemake/snakemake-github-action@v1.15.0
-      with:
-        directory: .tests
-        snakefile: workflow/Snakefile
-        stagein: mamba install -n snakemake -c conda-forge peppy
-        args: "--use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs cache --conda-frontend mamba"
+      - name: Test workflow
+        uses: snakemake/snakemake-github-action@v1.15.0
+        with:
+          directory: .tests
+          snakefile: workflow/Snakefile
+          stagein: mamba install -n snakemake -c conda-forge peppy
+          args: "--use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs cache --conda-frontend mamba"
 
-    - name: Test report
-      uses: snakemake/snakemake-github-action@v1.15.0
-      with:
-        directory: .tests
-        snakefile: workflow/Snakefile
-        stagein: mamba install -n snakemake -c conda-forge peppy
-        args: "--report report.zip"
+      - name: Test report
+        uses: snakemake/snakemake-github-action@v1.15.0
+        with:
+          directory: .tests
+          snakefile: workflow/Snakefile
+          stagein: mamba install -n snakemake -c conda-forge peppy
+          args: "--report report.zip"
+
+  Benchmarking:
+    runs-on: ubuntu-latest
+    needs: Testing
+    steps:
+      - uses: actions/checkout@v1
+
+      - name: Cache data
+        uses: actions/cache@v2
+        with:
+          path: |
+            .tests/data
+          key: "testdata-benchmarking" # TODO update key once we cache more than the data
+      
+      - name: Test workflow
+        uses: snakemake/snakemake-github-action@v1.15.0
+        with:
+          directory: .tests
+          snakefile: workflow/Snakefile
+          stagein: mamba install -n snakemake -c conda-forge peppy
+          args: "benchmark --use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs cache --conda-frontend mamba"
+      
+      - name: Check strain calling
+        run: |
+          cat .tests/results/benchmarking.csv
+          if grep mismatch .tests/results/benchmarking.csv
+          then
+            echo "Strain calling failed in some cases (see above)."
+            exit 1
+          else
+            echo "Strain calling was successful in all cases."
+          fi
