add test case to github actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -55,7 +55,7 @@ jobs:
     
     strategy:
       matrix:
-        rule: [all, benchmark_strain_calling, benchmark_assembly]
+        rule: [all, benchmark_strain_calling, benchmark_assembly, test_non_cov2]
 
     steps:
       - uses: actions/checkout@v2
@@ -215,6 +215,19 @@ jobs:
           else
             echo "Assembly was successful."
           fi
+
+      - name: Test non-sars-cov-2 coronaviruses
+        if: matrix.rule == 'test_non_cov2'
+        run: |
+          cat .tests/results/test-cases/non-sars-cov-2.csv
+          if (cat .tests/results/test-cases/non-sars-cov-2.csv | grep 'is sars-cov-2' > /dev/null)
+          then
+              echo "Workflow failed! A non-sars-cov-2 genome was identified as sars-cov-2 (see above)."
+              exit 1
+          else
+              echo "Workflow sucessfully identified samples as non-sars-cov-2 in all cases."
+          fi
+
 
       - name: Print disk space
         run: sudo df -h
