add benchmark assembly

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -100,3 +100,36 @@ jobs:
           else
             echo "Strain calling was successful in all cases."
           fi
+
+  Benchmark-Assembly:
+    runs-on: ubuntu-latest
+    needs: Testing
+    steps:
+      - uses: actions/checkout@v1
+
+      - name: Cache data
+        uses: actions/cache@v2
+        with:
+          path: |
+            .tests/data
+            .tests/resources/genomes
+          key: "testdata-benchmarking" # TODO update key once we cache more than the data
+      
+      - name: Test workflow
+        uses: snakemake/snakemake-github-action@v1.15.0
+        with:
+          directory: .tests
+          snakefile: workflow/Snakefile
+          stagein: mamba install -n snakemake -c conda-forge peppy
+          args: "benchmark_assembly --use-conda --show-failed-logs --cores 1 --resources ncbi_api_requests=1 --conda-cleanup-pkgs cache --conda-frontend mamba"
+
+      - name: Check assembly
+        run: |
+          cat .tests/results/benchmarking/strain-calling.csv
+          if (tail -n+2 .tests/results/benchmarking/strain-calling.csv | grep mismatch > /dev/null)
+          then
+            echo "Strain calling failed in some cases (see above)."
+            exit 1
+          else
+            echo "Strain calling was successful in all cases."
+          fi
