incl. check in matrix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,7 +44,7 @@ jobs:
     
     strategy:
       matrix:
-        rule: [all, benchmark_assembly] #[all, benchmark_strain_calling, benchmark_assembly]
+        rule: [all, benchmark_assembly]
     steps:
       - uses: actions/checkout@v2
 
@@ -186,12 +186,37 @@ jobs:
       #     snakefile: workflow/Snakefile
       #     stagein: mamba install -n snakemake -c conda-forge peppy
       #     args: "--use-conda --use-singularity --show-failed-logs --cores 2 --resources ncbi_api_requests=1 --conda-cleanup-pkgs cache --conda-frontend mamba"
+      
+      - name: Check strain calling
+        if: matrix.rule == 'benchmark_strain_calling'
+        run: |
+          cat .tests/results/benchmarking/strain-calling.csv
+          if (tail -n+2 .tests/results/benchmarking/strain-calling.csv | grep mismatch > /dev/null)
+          then
+            echo "Strain calling failed in some cases (see above)."
+            exit 1
+          else
+            echo "Strain calling was successful in all cases."
+          fi
 
+      - name: Check assembly
+        if: matrix.rule == 'benchmark_assembly'
+        run: |
+          cat .tests/results/benchmarking/assembly.csv
+          if [[ $(tail -1 .tests/results/benchmarking/assembly.csv) < 0.8 ]]
+          then
+            echo "Assembly bechmarking failed. There is at least one assembly where the contigs do not cover 80% of the original sequence (see above)."
+            exit 1
+          else
+            echo "Assembly was successful."
+          fi
+          
       - name: Change permissions for caching
         run: sudo chmod -R 755 .tests/.snakemake/conda
 
       - name: Get disk space
         run: sudo df -h
+
 
 
   # Strain-Calling-Benchmark:
