check benchmark results

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -217,6 +217,18 @@ jobs:
             echo "Strain calling was successful in all cases."
           fi
 
+      - name: Check pseudoassembly benchmark
+        if: matrix.rule == 'benchmark_assembly'
+        run: |
+          cat .tests/results/benchmarking/pseudoassembly.csv
+          if [[ $(tail -1 .tests/results/benchmarking/pseudoassembly.csv) < 0.95 ]]
+          then
+            echo "Pseudoassembly bechmarking failed. There is at least one assembly where the contigs do not cover 95% of the original sequence (see above)."
+            exit 1
+          else
+            echo "Pseudoassembly was successful."
+          fi
+
       - name: Check assembly bechmark
         if: matrix.rule == 'benchmark_assembly'
         run: |
